site_name: Web App CAA Documentation
site_description: Documentation for Web App CAA - Comunicazione Aumentativa e Alternativa
site_author: Daniele
site_url: https://dnviti.github.io/web-app-CAA

repo_name: dnviti/web-app-CAA
repo_url: https://github.com/dnviti/web-app-CAA

# Set docs directory to docs folder
docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji

plugins:
  - search
  - git-revision-date-localized:
      type: date

nav:
  - Home: index.md
  - Project Status:
      - Implementation Status: status.md
      - Development Roadmap: roadmap.md
      - AI Agent Guide: ai-agent-guide.md
  - Getting Started:
      - Quick Start: getting-started/quick-start.md
      - Installation: getting-started/installation.md
      - Configuration: getting-started/configuration.md
  - Architecture:
      - Overview: architecture/overview.md
      - Project Structure: architecture/structure.md
      - Database Schema: architecture/database.md
  - API Reference:
      - Authentication: api/authentication.md
      - Grid Management: api/grid.md
      - AI Services: api/ai.md
      - Swagger Implementation: api/swagger-implementation.md
  - Deployment:
      - Docker: deployment/docker.md
      - GitHub Pages: deployment/github-pages.md
  - Development:
      - Setup: development/setup.md
      - Testing: development/testing.md
      - Contributing: development/contributing.md
      - RBAC Migration: development/rbac-migration.md
      - Startup Migrations: development/startup-migrations.md
      - Clean Auth Refactoring: development/clean-auth-refactoring.md
      - CGO Issues: development/cgo-issue.md

copyright: Copyright &copy; 2025 Daniele
